repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: Runs the ruff linter
        entry: uv run ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: Runs the ruff formatter
        entry: uv run ruff format
        language: system
        types: [python]
      - id: ty
        name: Runs ty type checker
        entry: uv run ty check
        language: system
        types: [python]
      - id: pytest
        name: Runs pytest
        entry: uv run python -m pytest tests/
        language: system
        pass_filenames: false
        always_run: true
